name: 50mil
favicon: null
layout_spectrum: 0.8800496540497988
typography_spectrum: 0.7598273123148829
title: 50 Mil ManCave
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69508264-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dce4e7'
    - '#a19a94'
    - '#584d47'
    - '#1b1311'
    - '#12acc4'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
