name: 50mil
favicon: null
layout_spectrum: 0.8800496540497988
typography_spectrum: 0.7598273123148829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.11091682547703385
  lightness: 0.9368866730947047
  saturation: 0.22899038321338594
  rhythmicContrast: 0.29194390564225614
purpose: []
